### ISSUE TITLE
Is it possible to continue a crashed run?

### ISSUE THREAD

**Issue by dabitz** [BGI-Qingdao/TGS-GapCloser#19] opened 2020-10-06 07:34 UTC
I was running TGS-GapCloser for already one week without finishing, maybe because of high coverage with ccs reads? Also the run crashed. Is it possible to continue?

**Comment by cchd0001** [comment] 2020-10-07 07:34
Please make sure that previous runing is not exist before re-run it .

**Comment by dabitz** [comment] 2020-10-07 07:38
What do you mean? Can I just re-run with the same command and it will continue?

**Comment by adonis316** [comment] 2020-10-09 00:41
TGS-GapCloser was designed for closing gaps with low coverage of long reads. If the coverage is high, especially for large genomes, the process could be pretty slow for the read selection and error correction. Normally, 10x long reads for human, 3g, took 3~4 days with 16 threads. 

The run crashed possibly due to the large memory requirement. Please check your memory usage. One possible solution is that you could split the long-read dataset into small portions and then iteratively use one of them to close gaps.

The latest version supports continuing at where it crashed. However, you should make sure that the previous run completely stopped so that there is no possible interference.

**Comment by cchd0001** [comment] 2020-10-09 01:43
Yes , you can re-run with the same command and it will continue.

**Comment by dabitz** [comment] 2020-10-09 06:43
Thank you guys! I will try to continue the previous one and start a new one with less coverage.

**Closed** 2020-12-14 01:44 UTC
